---

container_runtime: podman

container_network_name: jenkins-net
container_network_subnet: 172.20.0.0/24
container_network_gateway: 172.20.0.1

jenkins_master_ip: 172.20.0.10
jenkins_agent_ip: 172.20.0.11

jenkins_master_container_name: jenkins-master
jenkins_master_image: docker.io/jenkins/jenkins:latest
jenkins_master_http_port: 8080
jenkins_master_agent_port: 50000

jenkins_master_data_dir: /opt/jenkins/master

jenkins_agent_container_name: jenkins-agent
jenkins_agent_image: docker.io/fabioviscusi/jenkins-agent:latest
jenkins_agent_data_dir: /opt/jenkins/agent

jenkins_agent_name: "podman-agent"
jenkins_agent_secret: "69d99ffa68541e0a1a23f6e096c2fa1df9b2a2b05862ca7456f06ce45c11e242"

jenkins_admin_user: "Admin"
jenkins_admin_password: "Admin1234!"