Vagrant.configure("2") do |config|
 config.vm.box = "bento/ubuntu-24.04"
 config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
 end

# Other Options

 config.vm.define "m1" do |m1|
  m1.vm.hostname = "m1"
  m1.vm.network "private_network", ip: "192.168.100.3"
 end

 config.vm.define "m2" do |m2|
  m2.vm.hostname = "m2"
  m2.vm.network "private_network", ip: "192.168.100.2"
  end
end