# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/rocky9"
  config.vm.box_version = ">= 4.0.0"
  config.vm.hostname = "devops-lab" 


  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 50000, host: 50000, host_ip: "127.0.0.1"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "devops-rocky"
    vb.memory = "4096"
    vb.cpus = 2
    
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/site.yml"
    ansible.verbose = false
    
    ansible.extra_vars = {
      python_interpreter: "/usr/bin/python3"
    }
  end

end
