Vagrant.configure("2") do |config|
 config.vm.box = "bento/ubuntu-24.04"
 #config.vm.synced_folder "./", "/home/vagrant"
 config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
 end

# Other Options

 config.vm.define "cluster" do |cluster|
  cluster.vm.hostname = "cluster"
  cluster.vm.network "private_network", ip: "192.168.100.3"
 end

 config.vm.define "kubectl" do |kubectl|
  kubectl.vm.hostname = "kubectl"
  kubectl.vm.network "private_network", ip: "192.168.100.2"
 end
end