Vagrant.configure("2") do |config|
 config.vm.box = "bento/ubuntu-24.04"
 #config.vm.synced_folder "./", "/home/vagrant"
 config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
 end

# Other Options

 config.vm.define "cluster" do |cluster|
  cluster.vm.hostname = "cluster"
  cluster.vm.network "private_network", ip: "192.168.100.3"
 end

 config.vm.define "kubectl" do |kubectl|
  kubectl.vm.hostname = "kubectl"
  kubectl.vm.network "private_network", ip: "192.168.100.2"
 end
   config.vm.provision "shell", inline: <<-SHELL
   apt update
   apt upgrade -y
   curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4
   chmod +x get_helm.sh
   bash get_helm.sh
   apt install docker.io -y
   usermod -aG docker vagrant
   [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.32.0/kind-linux-amd64
   chmod +x ./kind
   mv ./kind /usr/local/bin/kind
   curl -LO https://dl.k8s.io/release/v1.36.0/bin/linux/amd64/kubectl
   install -o vagrant -g vagrant -m 0755 kubectl /usr/local/bin/kubectl
   SHELL
end