Vagrant.configure("2") do |config|

  # Sistema operativo: Ubuntu 22.04 LTS
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "buntu"
 
  config.vm.provider "virtualbox" do |vb|
    vb.name   = "ubuntu"
    vb.memory = "2048"   # 2 GB RAM (minimo consigliato per AzuraCast)
    vb.cpus   = 2
  end
  config.vm.provision "shell", path: "oddEven.sh"
end