# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 1
  end

 config.vm.define "buntu-prod" do |m1|
  m1.vm.hostname = "m1"
  m1.vm.network "private_network", ip: "192.168.100.3"
 end

 config.vm.define "buntu" do |m2|
  m2.vm.hostname = "m2"
  m2.vm.network "private_network", ip: "192.168.100.2"
 end
  #config.vm.provision "ansible" do |ansible|
   # ansible.playbook = "esercizi.yml"
   # ansible.compatibility_mode = "2.0"
  #end
end
