apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
spec:
  containers:
  - name: demo
    image: busybox
    command: ["sleep", "3600"]
    env:
      - name: USER
        valueFrom:
          secretKeyRef:
            name: user
            key: user
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: user
            key: password   
